
name: Deploy to AWS S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Select Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Build
        run: ./build.sh

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
    
      - name: Print Working directory
        run: pwd

      - name: List files
        run: ls -a
      
      - name: Deploying to s3
        run: aws s3 cp ig-gmail-mcp-server.zip s3://${{ secrets.LAMBDAS_BUCKET }}/ig-gmail-mcp-server.zip

      - name: Updating lambda code
        run: aws lambda update-function-code --function-name ig-gmail-mcp-server-dev --s3-bucket ${{secrets.LAMBDAS_BUCKET}} --s3-key ig-gmail-mcp-server.zip